/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SavedCity = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'admin1' : IDL.Opt(IDL.Text),
});
export const TemperatureUnit = IDL.Variant({
  'fahrenheit' : IDL.Null,
  'celsius' : IDL.Null,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getSavedCities' : IDL.Func([], [IDL.Vec(SavedCity)], ['query']),
  'getUnit' : IDL.Func([], [TemperatureUnit], ['query']),
  'getWeather' : IDL.Func([IDL.Float64, IDL.Float64], [IDL.Text], []),
  'removeSavedCity' : IDL.Func([IDL.Text], [], []),
  'saveCity' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'searchCity' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setUnit' : IDL.Func([TemperatureUnit], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SavedCity = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lon' : IDL.Float64,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'admin1' : IDL.Opt(IDL.Text),
  });
  const TemperatureUnit = IDL.Variant({
    'fahrenheit' : IDL.Null,
    'celsius' : IDL.Null,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getSavedCities' : IDL.Func([], [IDL.Vec(SavedCity)], ['query']),
    'getUnit' : IDL.Func([], [TemperatureUnit], ['query']),
    'getWeather' : IDL.Func([IDL.Float64, IDL.Float64], [IDL.Text], []),
    'removeSavedCity' : IDL.Func([IDL.Text], [], []),
    'saveCity' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'searchCity' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setUnit' : IDL.Func([TemperatureUnit], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };